import Head from 'next/head'
import { Suspense,useRef } from "react"
import { useFrame,Canvas, useThree } from '@react-three/fiber'
import { Preload, ScrollControls, Scroll, useScroll, Image, useFBO, PerspectiveCamera } from '@react-three/drei'


function Images() {
  const { width, height } = useThree((state) => state.viewport)
  const data = useScroll()
  const group = useRef()
  useFrame(() => {
    group.current.children[0].material.zoom = 1 + data.range(0, 1 / 3) / 3
    group.current.children[1].material.zoom = 1 + data.range(0, 1 / 3) / 3
    group.current.children[2].material.zoom = 1 + data.range(1.15 / 3, 1 / 3) / 3
    group.current.children[3].material.zoom = 1 + data.range(1.15 / 3, 1 / 3) / 2
    group.current.children[4].material.zoom = 1 + data.range(1.25 / 3, 1 / 3) / 1
    group.current.children[5].material.zoom = 1 + data.range(1.8 / 3, 1 / 3) / 3
    group.current.children[5].material.zoom = 1 + data.range(0, 1 / 3) / 3
    group.current.children[6].material.zoom = 1 + (1 - data.range(2 / 3, 1 / 3)) / 3
  })
  return (
    <group ref={group}>
      <Image position={[-2, 0, 0]} scale={[4, height, 1]} url="/1.jpg"/>
      <Image position={[2, 0, 1]} scale={3} url="/1.jpg" />
      <Image position={[-2.3, -height, 2]} scale={[1, 3, 1]} url="/1.jpg" />
      <Image position={[-0.6, -height, 3]} scale={[1, 2, 1]} url="/1.jpg" />
      <Image position={[0.75, -height, 3.5]} scale={1.5} url="/1.jpg" />
      <Image position={[0, -height * 1.5, 2.5]} scale={[1.5, 1]} url="/1.jpg" />
      <Image position={[0, -height * 2 - height / 4, 0]} scale={[width, height / 2, 1]} url="/1.jpg" />
    </group>
  )
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="globe">
      <Canvas gl={{ antialias: false }} dpr={[1, 1.5]}>
      <Suspense fallback={null}>
        <ScrollControls damping={3} pages={5}>
          <Scroll>
            <Images />
          </Scroll>
          <Scroll html>
            <h1 style={{ position: 'absolute', top: '60vh', left: '0.5em' }}>Hallo</h1>
            <h1 style={{ position: 'absolute', top: '120vh', left: '60vw' }}>Welt</h1>
            <h1 style={{ position: 'absolute', top: '198.5vh', left: '0.5vw', fontSize: '40vw' }}>Hallo</h1>
            <h1 style={{ position: 'absolute', top: '30vh', left: '20vw' }}>Welt</h1>
          </Scroll>
        </ScrollControls>
        <Preload />
      </Suspense>
    </Canvas>
      </div>
    </div>
  )
}